version: "3.9"
services:
  database: 
    image: postgres
    restart: always
    ports:
      - "5040:5432"
    volumes:
      - /data/postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: mydatabase
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: masterkey

